#!/bin/sh

test -x $(which duplicity) || exit 0
. /root/.backup-config

for i in "${DIRECTORIES[@]}"
do
	DIRECTORIES_INCLUDE="$DIRECTORIES_INCLUDE --include /$i"
done

$(which duplicity) --encrypt-key ${KEY} --full-if-older-than 1W ${$DIRECTORIES_INCLUDE} --exclude '**' / sftp://root@${REMOTE}/${REMOTE_BACKUP_DIRECTORY}
$(which duplicity) remove-older-than 1Y --force sftp://root@${REMOTE}/${REMOTE_BACKUP_DIRECTORY}

unset DIRECTORIES
unset DIRECTORIES_INCLUDE
unset KEY
unset PASSPHRASE
unset REMOTE
unset REMOTE_BACKUP_DIRECTORY